/* tslint:disable */
/* eslint-disable */
/**
 * tasknet-api
 * This Browser API (v1) provides a comprehensive suite of endpoints for managing automated browser sessions and browser fingerprinting, enabling users to create and control browser instances with customizable configurations. The API supports sophisticated fingerprinting capabilities for specifying browser characteristics (including screen properties, device capabilities, and proxy settings), session management features for controlling browser instances (with VNC connectivity options and lease time management), extension management for enhancing browser functionality, and page control operations for automated browsing.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ajoor@tasker.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

